# Generated by Django 4.2.4 on 2023-08-18 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_scraper_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='company_salary',
            field=models.CharField(default='Salary not disclosed', max_length=100),
        ),
    ]
